services:
    backend:
        image: ghcr.io/${GHCR_OWNER}/trip2mk-api-gateway:${IMAGE_TAG:-latest}
        container_name: backend
        ports:
            - "8080:8080"
        depends_on:
            - feedback
            - mailing
            - main-app
            - postgres
    feedback:
        image: ghcr.io/${GHCR_OWNER}/trip2mk-feedback:${IMAGE_TAG:-latest}
        container_name: feedback
        ports:
            - "8081:8081"
        depends_on:
            - postgres
    mailing:
        image: ghcr.io/${GHCR_OWNER}/trip2mk-mailing:${IMAGE_TAG:-latest}
        container_name: mailing
        ports:
            - "8082:8082"
    main-app:
        image: ghcr.io/${GHCR_OWNER}/trip2mk-main-app:${IMAGE_TAG:-latest}
        container_name: main-app
        ports:
            - "8083:8083"
        depends_on:
            - postgres
    frontend:
        image: ghcr.io/${GHCR_OWNER}/trip2mk-frontend:${IMAGE_TAG:-latest}
        container_name: frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_DB: trip2mk
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data1
volumes:
  postgres_data:
