apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback
  namespace: trip2mk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback
  template:
    metadata:
      labels:
        app: feedback
    spec:
      containers:
        - name: feedback
          image: darsov2/feedback
          ports:
            - containerPort: 8081
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: db-url
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: DB_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: DB_PASSWORD
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: update
          - name: SPRING_JPA_SHOW_SQL
            value: "true"
          - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
            value: org.hibernate.dialect.PostgreSQLDialect