name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375
        env:
          DOCKER_HOST: tcp://localhost:2375

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v2
      with:
        context: ./backend/api-gateway
        push: true
        tags: darsov2/api:kube

    - name: Build and push feedback image
      uses: docker/build-push-action@v2
      with:
        context: ./backend/feedback-service
        push: true
        tags: darsov2/feedback:latest

    - name: Build and push mailing image
      uses: docker/build-push-action@v2
      with:
        context: ./backend/mailing-service
        push: true
        tags: darsov2/mailing:kube

    - name: Build and push main-app image
      uses: docker/build-push-action@v2
      with:
        context: ./backend/main-app
        push: true
        tags: darsov2/main-app:kube

    - name: Build and push frontend image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: darsov2/trip2mk-front:kube
